UPDATE_MODE_RAISE_ONLY = "raise_only"
UPDATE_MODE_RECALCULATE = "recalculate"
UPDATE_MODE_INITIAL_ONLY = "initial_only"

PRIORITY_POLICY_UPDATE_MODES = {
    UPDATE_MODE_RAISE_ONLY,
    UPDATE_MODE_RECALCULATE,
    UPDATE_MODE_INITIAL_ONLY,
}


SOURCE_PRIORITY_IGNORE = "ignore"
SOURCE_PRIORITY_PREFER = "prefer"

SOURCE_PRIORITY_MODES = {
    SOURCE_PRIORITY_IGNORE,
    SOURCE_PRIORITY_PREFER,
}


FALLBACK_SEVERITY_MAPPING = "severity_mapping"
FALLBACK_FIXED_PRIORITY = "fixed_priority"

PRIORITY_POLICY_FALLBACK_MODES = {
    FALLBACK_SEVERITY_MAPPING,
    FALLBACK_FIXED_PRIORITY,
}
