[pytest]
testpaths = tests
addopts = -ra --strict-config --strict-markers
python_files = test_*.py
norecursedirs =
    tests/postgresql
markers =
    postgresql: tests that require PostgreSQL database backend
