"""Central limits for deterministic and bounded orchestration evaluation."""

MAX_CONDITION_DEPTH = 20
MAX_CONDITION_NODES = 256
MAX_FIELD_REFERENCE_LENGTH = 256
MAX_REGEX_PATTERN_LENGTH = 512
MAX_REGEX_INPUT_LENGTH = 16_384
MAX_TEMPLATE_LENGTH = 8_192
MAX_TEMPLATE_EXPRESSIONS = 64
MAX_TEMPLATE_EXPRESSION_LENGTH = 512
MAX_TEMPLATE_OUTPUT_LENGTH = 16_384
MAX_TEMPLATE_FILTERS = 8
MAX_VARIABLES = 128
MAX_VARIABLE_NAME_LENGTH = 64
MAX_VARIABLE_VALUE_LENGTH = 16_384
MAX_JSON_PATH_LENGTH = 512
MAX_SPLIT_PARTS = 256
MAX_TRACE_VALUE_LENGTH = 512
