apiVersion: v2
name: incidentrelay
description: On-call scheduling, alert routing and incident notification service
type: application
version: 2.0.0
appVersion: "2.0"
kubeVersion: ">=1.23.0-0"
home: https://github.com/roxy-wi/IncidentRelay
sources:
  - https://github.com/roxy-wi/IncidentRelay
keywords:
  - oncall
  - incident
  - alerting
  - notifications
