apiVersion: v2
name: incidentrelay
description: On-call scheduling, alert routing and incident notification service
type: application
version: 2.2.0
appVersion: "2.2"
kubeVersion: ">=1.23.0-0"
home: https://github.com/roxy-wi/IncidentRelay
sources:
  - https://github.com/roxy-wi/IncidentRelay
keywords:
  - oncall
  - incident
  - alerting
  - notifications
annotations:
  org.opencontainers.image.source: https://github.com/roxy-wi/IncidentRelay
  org.opencontainers.image.description: IncidentRelay Helm chart for on-call scheduling, alert routing and incident response
  org.opencontainers.image.licenses: MIT
