ROUTE_ONLY = "route_only"
SERVICE_POLICY = "service_policy"
SERVICE_POLICY_PLUS_ROUTE = "service_policy_plus_route"

NOTIFICATION_CHANNEL_MODE_PATTERN = (
    r"^(route_only|service_policy|service_policy_plus_route)$"
)
NOTIFICATION_CHANNEL_MODES = {
    ROUTE_ONLY,
    SERVICE_POLICY,
    SERVICE_POLICY_PLUS_ROUTE,
}


EVENT_NOTIFICATION = "notification"
EVENT_REMINDER = "reminder"
EVENT_ESCALATION = "escalation"

NOTIFICATION_POLICY_EVENT_TYPES = {
    EVENT_NOTIFICATION,
    EVENT_REMINDER,
    EVENT_ESCALATION,
}

NOTIFICATION_POLICY_EVENT_ALIASES = {
    "update": EVENT_NOTIFICATION,
}

DEFAULT_NOTIFICATION_POLICY_EVENT_TYPES = [
    EVENT_NOTIFICATION,
    EVENT_REMINDER,
    EVENT_ESCALATION,
]

