{{- if not .Values.existingConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "incidentrelay.configSecretName" . }}
  labels:
    {{- include "incidentrelay.labels" . | nindent 4 }}
type: Opaque
stringData:
  incidentrelay.conf: |
    {{- include "incidentrelay.config" . | trim | nindent 4 }}
{{- end }}
